enter_answer: 'Enter answer:'
possible_answers: "Possible answers:"
insane: Sorry, but u are insane! Bye!
yes_or_no: 'Type "yes" or "no" please:'
answer_again: Sorry, but i cant get it. Can you answer again?
ask_again: 'Try to choose from suggested answers. u can answer by typing message or number of hot variant. So, the question is:'