question:
  text: I can help you with answers on all your related questions and help you to find a great job
  answers: # for exact match with one of answer variants 
    - text: Lets talk #variant example
      question:
        text: Please enter your name
        data: name
        question:
          text: Hello %user_name%! How can we reach out to you?
          data: contact_type
          answers: 
            - text: Phone
              question: 
                label: get_phone
                text: Please type your phone number
                data: phone # this question should receive specific data
                question:
                  text: What is the best time we can reach out to you?
                  data: contact_time
                  answers: 
                    - text: ASAP
                      question: &confirm_contact # copy node with YAML
                        label: confirm_contact
                        text: We are going to contact you using %contact%
                        answers: 
                          - text: Yes, Please
                            final: # serves like an command 'exit'
                              text: Thanks! Bye!
                              prefix: happy
                          - text: Sorry, wrong %contact_type%
                            branch: get_phone # GO TO branch with label 'get_phone'
                    - text: Morning
                      branch: confirm_contact
                    - text: Afternoon
                      branch: confirm_contact
                    - text: Evening
                      branch: confirm_contact
            - text: Email
              question:
                label: get_email
                text: Please type your email address
                data: email
                question:
                  <<: *confirm_contact # paste node with YAML
                  answers: 
                    - text: Yes, Please
                      final: 
                        text: Thanks! Bye!
                        prefix: happy
                    - text: Sorry, wrong %contact_type%
                      branch: get_email
            - text: i dont wont to be contacted
              question:
                text: Said to hear that. Whenever you change your mind - feel fre to send me a message  
                final:
                  text: Hope to hear you soon! Bye!
